# Database components relative to root. Loaded with test_trained_model.yaml into testing_data.py and test_trained_model.py

testsets_path: logs

st_lucia:
  subset: images/test
  database: database
  query: queries
  img_ext: jpg

tokyo247:
  subset: images/test
  database: database
  query: queries
  img_ext: jpg

msls:
  subset: test
  database: database
  query: queries
  img_ext: jpg
