root: '/scratch/gj2148/VPR4LQQ'
test_runs: 5

model_IO:
  weights_path: parameters/RA_VPR
  logs_path: logs/tensorboard_logs

test_data:
  name: "Nordland"
  resolution:    # 2 number list enforces dimension; 1 number chooses height and preserves aspect ratio
    180p: 180    # [height, width]
    240p: 240
    360p: 360
    480p: 480
  test_res: 240p

train_conf:
  batch_size: 15
  num_worker: 5
  num_cluster: 64
  lr: 0.000001
  lr_decay: 0.000000000002
  exponential_gamma: 0.99999
  data:
    name: pitts250k
    resolution: 180p
    qp: -1
  cluster:
    descriptor_num: 500000
    descriptor_per_image: 100
    dimension: 512
  loss:
    distill: false
    vlad: false
    triplet: false
  triplet_loss:
    posDistThr: 30
    nonTrivPosDistSqThr: 20
    nPosSample: 1
    nNegSample: 5
    margin: 0.2

vpr:
  topk:
    - 1
    - 2
    - 5
    - 10
    - 15
    - 20
    - 25
  threshold:
    - 25
  global_extractor:
    # If netvlad is used, then remaining methods are ignored given GlobalExtractor preprocess=False
    netvlad:
      use: true
      ckpt_path:  'parameters/netvlad/paper/checkpoints'
      arch: 'vgg16'
      num_clusters: 64
      pooling:  'netvlad'
      vladv2: false
      nocuda: false
    MixVPR:
      use: true
      ckpt_path: 'parameters/MixVPR/ckpts/resnet50_MixVPR_4096_channels(1024)_rows(4).ckpt'
      resized_img_size: [320, 320]    # For MixVPR's pretrained weights, this value cannot change
      cuda: true
    AnyLoc:
      use: true
      max_image_size: 1024    # To prevent out of memory
      desc_layer: 31
      desc_facet: 'value'    # one of "query", "key", "value", "token"
      num_clusters: 32
      domain: 'indoor'    # one of "aerial", "indoor", "urban"
      cache_dir: 'parameters/AnyLoc/demo/cache'
      cuda: true
