root: '/mnt/data/VPR4LQQ'

data:
  rate: 30
  slice:
    FOV: 90
    PITCH:
      num: 1
      range: 20
    YAW:
      num: 18
    SHAPE:
      # height: 810
      # width: 1440
      height: 540
      width: 960
  compression:
    prepocess: true
    QP:
      min: 30
      max: 50
      interval: 3
    resolution:
      203p: [203,360]
      405p: [405,720]
      810p: [810,1440]

train:
  video:
    sequence_num: 3
  start_epoch: 0
  nepoch: 10
  evalEvery: 1
  batch_size: 3
  num_worker: 3
  num_cluster: 64
  cacheRefreshRate: 1000
  nGPU: 3
  resume: true
  lr: 0.00001
  lr_decay: 0.00000000002
  exponential_gamma: 0.99999
  data:
    resolution: 203p
    qp: 30
  cluster:
    descriptor_num: 500000
    descriptor_per_image: 100
    dimension: 512
  loss:
    distill: true
    vlad: false
    triplet: false
  triplet_loss:
    posDistThr: 15
    nonTrivPosDistSqThr: 2
    nPosSample: 1
    nNegSample: 5
    margin: 0.2

vpr:
  topk:
    - 1
    - 2
    - 5
    - 10
    - 15
    - 20
  threshold:
    - 1
    - 2
    - 5
    - 10
  global_extractor:
    netvlad:
      use: true
      ckpt_path:  'parameters/netvlad/paper'
      arch: 'vgg16'
      num_clusters: 64
      pooling:  'netvlad'
      vladv2: false
      nocuda: false
  local_feature: 'superpoint'